print("Enter First number: ")
firstnumber =int(input())
print("Enter Second number: ")
secondnumber =int(input())
print(str(firstnumber) + "+" + str(secondnumber) + "=" + str(firstnumber + secondnumber))
print(str(firstnumber) + "-" + str(secondnumber) + "=" + str(firstnumber - secondnumber))
print(str(firstnumber) + "*" + str(secondnumber) + "=" + str(firstnumber * secondnumber))
print(str(firstnumber) + "/" + str(secondnumber) + "=" + str(firstnumber / secondnumber))
print(str(firstnumber) + "%" + str(secondnumber) + "=" + str(firstnumber % secondnumber))